type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
name = "fixtwitter"
compatibility_date = "2022-01-30"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
